### PR TITLE
added some instructions and usage

### PR DESCRIPTION
**Pull request by Rishon73**

### CODE REVIEW

**Comment by panama69** [comment]
The readme says this is a Java LeanFT script.  But this looks like a Vugen TruClient script when I look at the source code.

were you thinking of different scripts?

**Comment by Rishon73** [comment]
You're right, I had something else in mind :-)
Do I need to create a new push request for the update?

**Comment by panama69** [comment]
Is there a reason you used HTML in the readme file rather than normal markdown?
[Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
[Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

No, you do not need to do a new pull.  You can continue to make changes/commits and they will show as part of the pull.

If you want to really have fun, you can put in emojis also found www.emoji-cheat-sheet.com
:jack_o_lantern:

**Comment by Rishon73** [comment]
Emojis like that :fu: 

:stuck_out_tongue_winking_eye: :stuck_out_tongue_winking_eye: :stuck_out_tongue_winking_eye:

**Review by panama69 — APPROVED** [review]
looks good.

**Pull request merged**
